### ISSUE TITLE
Pastel Wonderland Checklist

### ISSUE THREAD

**Issue by asoji** [devOS-Sanity-Edition/pastelwonderland#40]
# Things for the upcoming version, due before Blanketcon

# Blocks/Plants
- [ ] Pillow Block that can be thrown
- [ ] Taffy Block
    - Physics-wise, behaves like a bed?
- [ ] Purple spore puffs that can cause you to take damage when in proximity [toxic]
- [ ] Blue glow mushrooms
- [ ] Blue /Green decorational plants

WIP in planning for this one because forest stuff ideas is not done!

# Items

- [ ] Taffy rope
- [ ] Taffy leads
- [ ] Waxpaper

Also WIP in planning

## Foods related
- [x] Taffy [soft candy basically]
- [x] Hard Candy
- [x] Cotton Candy
- [ ] Sugar Ore
- [ ] Pastel Ore
- [ ] Spicy Sugar Cane
- [x] Peanut Brittled
- [x] Peanut
- [x] Peanut Butter
- [x] Ice Cream

## Foods related tech/armour?

In extension by default, all the armour should have corresponding tools too.

- [ ] Candy Machine for making Candy related stuff
- [ ] Soft Candy Armour
    - Made out of Cotton Candy Blocks
- [ ] Hard Candy Armour
    - Jolly-rancher-like, idk, there wasn't much on the ideaboard regarding this one.
- [ ] Pillow Armour
    - Made out of pillows, reduces fall damage, makes a soft fall sound when landed

# Worldgen

## Above ground

- [ ] Plains-like, potentially meadow clone
    - Sparse trees with flowers and plants
- [ ] Dark-oak like forest
- [ ] Tiaga-like forest
- [ ] Desert-like
- [ ] Mesa-like with Pastel blocks
- [ ] Peanut biome that has an ice-spikes like form

## Underground
- [ ] Lush-like caves with our plants

## Structures
- [ ] King of the hill pillow towers
- [ ] Burnable cotton villages

# Entities

## Passive/neutral
- [ ] Mallards. Only attack if you attack them.
- [ ] Nubert, my man!
- [ ] Plushies. They don't do much, other than heart particles when near them.

## Hostile
- none planned[?]

# Other
- [ ] Revamp textures to not be vanilla-edits
    - might be CTM-able
- [ ] Custom small soundtrack made by @MrGlockenspiel [if he can do it. if he can't it's fine]

**Comment by asoji** [comment]
people working on this: please refer to the ideaboard and adjust as necessary.

**Comment by asoji** [comment]
also for anyone in devOS who wants to contribute: go to the development channel and join the BlanketCon thread. Easy channel access through pinned messages, or by click on the Threads button and then BlanketCon.

**Comment by asoji** [comment]
Foods added w/o textures:
- Peanut
- Peanut Butter
- Peanut Brittle Ice Spikes
- All Cotton Candy
- All Hard Candy

Foods added w/ textures:
- All taffy candy [yay]
